version: "3.9"
services:
  build-readme:
    build: .
    container_name: build-readme
    image: ghcr.io/ttw225/ttw225:latest
    volumes:
      - ./README.md:/README.md
      - ./cat_readme/status.json:/src/status.json