name: CI

on:
  push:
    paths:
      - "cat_readme/**"
      - ".github/workflows/ci.yml"
  pull_request:
    paths:
      - "cat_readme/**"
      - ".github/workflows/ci.yml"

jobs:
  analysis:
    name: Lint + Security + Types + Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cat_readme
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
        with:
          version: "latest"
          enable-cache: true
          cache-dependency-glob: "cat_readme/uv.lock"
      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - name: Check lockfile consistency
        run: uv lock --check
      - name: Install Dependencies
        run: uv sync --frozen
      - name: ruff
        run: uv run --frozen ruff check src
      - name: pylint
        run: uv run --frozen pylint src
      - name: mypy
        run: uv run --frozen mypy src
      - name: bandit
        run: uv run --frozen bandit -r src

      - name: pytest
        run: uv run --frozen python3 -m pytest -vv --cov-report=term-missing --cov=src tests/
