name: CI

on:
  push

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cat_readme
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
          enable-cache: true
          cache-dependency-glob: "cat_readme/uv.lock"
      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"
      - name: Install Dependencies
        run: uv sync --frozen
      - name: Check lockfile consistency
        run: uv lock --check
      - name: ruff
        run: uv run --frozen ruff check src
      - name: pylint
        run: uv run --frozen pylint src
      - name: mypy
        run: uv run --frozen mypy src
  analysis:
    name: Analysis
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cat_readme
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
          enable-cache: true
          cache-dependency-glob: "cat_readme/uv.lock"
      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"
      - name: Install Dependencies
        run: uv sync --frozen
      - name: bandit
        run: uv run --frozen bandit -r src
